version: '2.1'

services:
  master:
    container_name: "citus_master"
    image: 'citusdata/citus:8.1.1'
    ports: ["${CITUS_MASTER_EXTERNAL_PORT:-5433}:5432"]
    labels: ['com.citusdata.role=Master']
  worker:
    image: 'citusdata/citus:8.1.1'
    labels: ['com.citusdata.role=Worker']
    depends_on: { manager: { condition: service_healthy } }
  manager:
    container_name: "citus_manager"
    image: 'citusdata/membership-manager:0.2.0'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    depends_on: { master: { condition: service_healthy } }
